---
- name: Clone the latest version of the repository (git module)
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: master # The branch to checkout
    force: yes    # Ensures the repo is clean on re-runs
  tags: clone_code

- name: Start Docker Compose stack (build and run - using v2 module)
  community.docker.docker_compose_v2:
    project_dir: "{{ repo_dest }}"
    build: yes    # Build the microservices using the Dockerfiles in the cloned repo
    state: present # Ensures containers are created and running
  tags: run_app